.TH manila 7

.SH NAME
   /\\\\/\\\\  /\\\\  /\\\\  /\\\\ /\\\\ /\\\\ /\\\\
  //  V  \\//  \\//  \\// /// /// ///  \\
 // /\\_/\\ V /\\ V /\\ V /// /// /_V /\\ \\
 V_/     \\_/``\\_/  \\_/ V_/ V_____/``\\_\\

.SH SYNOPSIS
Manuel Nila - Programmer, Creator, and Artist.

.SH DESCRIPTION
Hello! I'm Manuel Nila, I love exploring novel uses of technology and building whimsical experiences.

.SH CONTACT
hi@manila.me

.SH SEE ALSO

.BR https://github.com/manila

.SH ANALYTICS OPT-OUT

This page uses Google Analytics, to opt out of tracking on this and all other website that utilize GA install the Google Analytics Opt-out Browser Add-on from Google.

.BR https://tools.google.com/dlpage/gaoptout
