.TH manila.me 7 2022-05-08 GNU

.SH NAME
   /\\\\/\\\\  /\\\\  /\\\\  /\\\\ /\\\\ /\\\\ /\\\\
  //  V  \\//  \\//  \\// /// /// ///  \\
 // /\\_/\\ V /\\ V /\\ V /// /// /_V /\\ \\
 V_/     \\_/``\\_/  \\_/ V_/ V_____/``\\_\\

.SH DESCRIPTION
 Hello!, I'm Manuel Nila, an asipiring software engineer who loves whimsical and novel uses of technology.

 I'm passionate about open-source and learning new things

.SH CONTACT
 hi@manila.me

.SH SEE ALSO

.BR https://github.com/manila
